window:
  decorations: none
  startup_mode: Maximized
  opacity: 0.75
font:
  normal:
    family: JetBrainsMono Nerd Font Mono
  size: 7.0
cursor:
  style:
    shape: Beam
    blinking: On
bell:
  animation: EaseOutExpo
  color: '#ff0000'
  command: None
