[[language]]
name = "rust"
auto-format = true

[[language]]
name = "go"
auto-format = true
# comment-token = "#"
# formatter = { command = "gofmt" , args = ["--stdin"] }
# language-servers = [ "gopls" ]

[[language]]
name = "markdown"
rulers = [80]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = true
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

